name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK + accept licenses
        uses: android-actions/setup-android@v3

      - name: Show gradle.properties (debug)
        run: |
          echo "---- gradle.properties ----"
          cat gradle.properties || true
          echo "---------------------------"

      - name: Build Debug APK (verbose)
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon --stacktrace --info clean :app:assembleDebug | tee gradle-log.txt
        env:
          TERM: dumb

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload build log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-log
          path: gradle-log.txt
